modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minezero"
type="required"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="required"
versionRange="[3.20,)"
ordering="NONE"
side="BOTH"

# Mixin 配置 —— 必须声明，否则 FML 不会加载 mixins.json
[[mixins]]
config = "${mod_id}.mixins.json"
